### ISSUE TITLE
on challenge task looks not working

### ISSUE THREAD

**Issue by aliceinwire** [goldfndr/tasker-habitrpg#3]
if i give the id of challenge task is creating a new task with the id as the task name instead of scoring the challenge task.
With no challenge task is working good.

**Comment by goldfndr** [comment]
I tried just now a `score_task` of _Browse HabitRPG issue queue_, a habit in the _Become a Legendary Blacksmith_ challenge from _The developers guild_ and it worked just fine. So I'm guessing that you somehow misspelled the ID. Could you try again? If it makes a new task then could you use the [Data Display Tool](https://oldgods.net/habitrpg/habitrpg_user_data_display.html) and verify that the IDs aren't different?

**Comment by goldfndr** [comment]
Not reproducible, closing. With API v3 and its reporting success as true or false, any misspelled ID will cause an alert to show up,
